const PRODUCTS_FETCH = "PRODUCTS_FETCH"
const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS"
const PRODUCTS_FETCH_FAIL = "PRODUCTS_FETCH_FAIL"

const CART_FETCH = "CART_FETCH"
const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS"
const CART_FETCH_FAIL = "CART_FETCH_FAIL"

const ADD_CART = "ADD_CART"
const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
const ADD_CART_FAIL = "ADD_CART_FAIL"

const REMOVE_CART = "REMOVE_CART"
const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS"
const REMOVE_CART_FAIL = "REMOVE_CART_FAIL"

export {
  PRODUCTS_FETCH,
  PRODUCTS_FETCH_SUCCESS,
  PRODUCTS_FETCH_FAIL,
  CART_FETCH,
  CART_FETCH_SUCCESS,
  CART_FETCH_FAIL,
  ADD_CART,
  ADD_CART_SUCCESS,
  ADD_CART_FAIL,
  REMOVE_CART,
  REMOVE_CART_SUCCESS,
  REMOVE_CART_FAIL,
}
