export const PRODUCTS_FETCH = "PRODUCTS_FETCH"
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS"
export const PRODUCTS_FETCH_FAIL = "PRODUCTS_FETCH_FAIL"

export const CART_ITEMS_FETCH = "CART_ITEMS_FETCH"
export const CART_ITEMS_FETCH_SUCCESS = "CART_ITEMS_FETCH_SUCCESS"
export const CART_ITEMS_FETCH_FAIL = "CART_ITEMS_FETCH_FAIL"
