export const PRODUCTS_FETCH = "PRODUCTS_FETCH"
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS"
export const PRODUCTS_FETCH_FAIL = "PRODUCTS_FETCH_FAIL"

export const CART_ITEMS_FETCH = "CART_ITEMS_FETCH"
export const CART_ITEMS_FETCH_SUCCESS = "CART_ITEMS_FETCH_SUCCESS"
export const CART_ITEMS_FETCH_FAIL = "CART_ITEMS_FETCH_FAIL"

export const ADD_CART = "ADD_CART"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const ADD_CART_FAIL = "ADD_CART_FAIL"

export const REMOVE_CART = "REMOVE_CART"
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS"
export const REMOVE_CART_FAIL = "REMOVE_CART_FAIL"
